baseurl: https://xvishaldongre.github.io/exsentences/
title: 
paginate: 6
theme: PaperMod

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpored: false

#googleAnalytics: G-747PCZ7M3S

minify:
  disableXML: true
  minifyOutput: true

params:
  quote: There's no such thing as mandatory education. You can make people sit in chair, but they won't learn anything. At some point people have to voluntarily make the choice to learn.
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  title: WORD IN A SENTENCE

  description: "Get example sentences"
  author: "Vishal Dongre"

  images: "<link or path of image for opengraph, twitter-cards>"

  ShowReadingTime: true
  ShowShareButtons: true
  comments: false
  defaultTheme: auto
  disableThemeToggle: false
  disableSpecial1stPost: false

  # profile-mode
  profileMode:
    enabled: true # needs to be explicitly set
    title: Welcome to WORD IN A SENTENCE
    # imageUrl: 'https://i.imgur.com/k9WdbK2.png'
    # imageTitle: my image

  # home-info mode
  homeInfoParams:
    Title: "Hi there \U0001F44B"
    Content: Welcome to WORD IN A SENTENCE

  socialIcons:
    - name: github
      url: "https://github.com/xvishaldongre/"
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.3
    minMatchCharLength: 0
    keys: ["summary"]

menu:
  main:
    - name: Home
      url: /
      weight: 5
    - name: About
      url: /about/
      weight: 7
    - name: Search
      url: /search/
      weight: 10

taxonomies:
  category: categories
  tag: tags
  series: series
  archive: archives
  summary: summary

DefaultContentLanguage: en
copyright: Made with ❤ by Vishal Dongre
# copyright: It is a miracle that curiousity survives formal education. - Albert Einstein
languages:
  en:
    languageName: "English"
    weight: 1

pluralizelisttitles: false
publishDir: docs

outputs:
  home:
    - HTML
    - RSS
    - JSON # is necessary
